### ISSUE TITLE
Is this still being maintained?

### ISSUE THREAD

**Issue by wagenaartje** [maxogden/ndjson#20]
Is this library still being maintained? If it isn't, could I become the maintainer? I want to create more functionality. For example, sync parse and serialize methods. These are fairly easy to implement.

Please met me know.

**Comment by cjk** [comment]
Also looking for a maintained ndjson-library for nodejs. All the official ones seem to be abandoned.

**Comment by finnp** [comment]
There is not too much to be maintained here. I think adding sync methods could be nice, so feel free to create a pull request for that. I'm also happy to help out with that.
